import {
  VITE_EMAILJS_SERVICE_ID,
  VITE_EMAILJS_PUBLIC_KEY,
  VITE_EMAILJS_TEMPLATE_SENDER,
  VITE_EMAILJS_TEMPLATE_RECEIVER,
} from "@/env/local";

const EMAILJS_CONFIG = {
  SERVICE_ID:
    process.env.NEXT_PUBLIC_EMAILJS_SERVICE_ID || VITE_EMAILJS_SERVICE_ID || "",
  TEMPLATE_ID_SENDER:
    process.env.NEXT_PUBLIC_EMAILJS_TEMPLATE_SENDER || VITE_EMAILJS_TEMPLATE_SENDER || "",
  TEMPLATE_ID_RECEIVER:
    process.env.NEXT_PUBLIC_EMAILJS_TEMPLATE_RECEIVER || VITE_EMAILJS_TEMPLATE_RECEIVER || "",
  PUBLIC_KEY:
    process.env.NEXT_PUBLIC_EMAILJS_PUBLIC_KEY || VITE_EMAILJS_PUBLIC_KEY || "",
};
if (
  !EMAILJS_CONFIG.SERVICE_ID ||
  !EMAILJS_CONFIG.TEMPLATE_ID_SENDER ||
  !EMAILJS_CONFIG.TEMPLATE_ID_RECEIVER ||
  !EMAILJS_CONFIG.PUBLIC_KEY
) {
  console.error(
    "Erro: Credenciais EmailJS ausentes. Configure .env.local ou ajuste src/env/local.ts"
  );
}

export default EMAILJS_CONFIG;
